{
 "title": "Grafana Dashboard for Veeam Enterprise Manager",
 "description": "Grafana Dashboard for Veeam Backup for Microsoft Office 365 Dashboard - Works only with v4.0 of VBO",
 "tags": [
  "Veeam",
  "Enterprise Manager"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "enterprisemanager",
    "label": "Enterprise Manager",
    "query": "SHOW TAG VALUES FROM veeam_em_overview WITH KEY=host"
   },
   {
    "name": "veeamserver",
    "label": "Veeam Backup Server",
    "query": "SHOW TAG VALUES FROM veeam_em_job_sessions WITH KEY=veeamVBR"
   },
   {
    "name": "repository",
    "label": "Backup Repository",
    "query": "SHOW TAG VALUES FROM veeam_em_overview_repositories WITH KEY=veeamRepositoryName WHERE \"veeamVBR\" =~ /$veeamserver/"
   },
   {
    "name": "backupjob",
    "label": "Backup Job",
    "query": "SHOW TAG VALUES FROM veeam_em_job_sessions WITH KEY=veeamBackupSessionsName WHERE \"veeamVBR\" =~ /$veeamserver/"
   },
   {
    "name": "replicajob",
    "label": "Replica Job",
    "query": "SHOW TAG VALUES FROM veeam_em_job_sessions WITH KEY=veeamReplicaSessionsName WHERE \"veeamVBR\" =~ /$veeamserver/"
   },
   {
    "name": "backupvm",
    "label": "Protected VM",
    "query": "SHOW TAG VALUES FROM veeam_em_job_sessionsvm WITH KEY=veeamBackupSessionsVmDisplayName WHERE \"veeamVBR\" =~ /$veeamserver/"
   },
   {
    "name": "replicavm",
    "label": "Replicated VM",
    "query": "SHOW TAG VALUES FROM veeam_em_job_sessionsvm WITH KEY=veeamReplicaSessionsVmDisplayName WHERE \"veeamVBR\" =~ /$veeamserver/"
   },
   {
    "name": "veeamversion",
    "query": "SHOW TAG VALUES FROM veeam_em_backup_servers WITH KEY=veeamBackupServersVersion WHERE \"veeamVBR\" =~ /$veeamserver/"
   },
   {
    "name": "veeamversionM",
    "query": "SHOW TAG VALUES FROM veeam_em_backup_servers WITH KEY=veeamBackupServersVersionM WHERE \"veeamVBR\" =~ /$veeamserver/"
   }
  ]
 },
 "panels": [
  { "title": "Enterprise Manager - Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "content": "![Veeam Backup Enterprise Manager - Dashboard](https://www.jorgedelacruz.es/wp-content/uploads/2020/01/enterprise-manager-1.png)\n\n\n\n",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_em_overview",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamBackupServers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
     ]
    }
   ]
  },
  {
   "title": "Backup Servers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_em_overview",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamBackupServers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
     ]
    }
   ]
  },
  {
   "title": "Repository Servers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_em_overview",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamRepositoryServers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
     ]
    }
   ]
  },
  {
   "title": "Proxy Servers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_em_overview",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamProxyServers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
     ]
    }
   ]
  },
  {
   "title": "Scheduled Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_em_overview",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamScheduledJobs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
     ]
    }
   ]
  },
  {
   "title": "Backup Repository - Usage Capacity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "alias": "$tag_veeamRepositoryName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"veeamRepositoryCapacity\") - mean(\"veeamRepositoryFreeSpace\")) * (100 / mean(\"veeamRepositoryCapacity\"))  FROM  \"veeam_em_overview_repositories\" WHERE (\"veeamRepositoryName\" =~ /^$repository$/) AND $timeFilter GROUP BY time($__interval), \"veeamRepositoryName\"  fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Successful VMs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_em_overview",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamSuccessfulVmLastestStates" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
     ]
    }
   ]
  },
  {
   "title": "Warning VMs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_em_overview",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamWarningVmLastestStates" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
     ]
    }
   ]
  },
  {
   "title": "Failed VMs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_em_overview",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamFailedVmLastestStates" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
     ]
    }
   ]
  },
  {
   "title": "Protected VMs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_veeamMaxDurationBackupJobName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamMaxDurationBackupJobName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_em_overview_vms",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamProtectedVms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
     ]
    }
   ]
  },
  {
   "title": "Replicated VMs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_veeamMaxDurationBackupJobName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamMaxDurationBackupJobName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_em_overview_vms",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamReplicatedVms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$enterprisemanager$/" }
     ]
    }
   ]
  },
  { "title": "Backup Repositories - Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$repository",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4.8, "x": 0, "y": 10 },
   "repeat": "repository",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_repository",
     "query": "SELECT (mean(\"veeamRepositoryCapacity\") - mean(\"veeamRepositoryFreeSpace\")) * (100 / mean(\"veeamRepositoryCapacity\"))  FROM  \"veeam_em_overview_repositories\" WHERE (\"veeamRepositoryName\" =~ /^$repository$/ AND \"veeamVBR\" =~ /^$veeamserver$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "capacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "repository", "operator": "=~", "value": "/^$repository$/" }
     ]
    }
   ]
  },
  {
   "title": "$veeamserver v$veeamversionM ($veeamversion) - Veeam Backup Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "veeamserver"
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage in %" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Privileged_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Privileged Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% User Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Interrupt Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$veeamserver$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes", "label": "RAM Usage in bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Available Bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "Pool_Nonpaged_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Pool non-paged Bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "Pool_Paged_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Pool paged Bytes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$veeamserver$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 20 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "win_system",
     "query": "SELECT \"System_Up_Time\" FROM \"win_system\" WHERE (\"host\" =~ /^$vboserver$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "System_Up_Time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$veeamserver$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 20 },
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT 100 - (mean(\"Percent_Free_Space\")) FROM \"win_disk\" WHERE (\"host\" =~ /^$veeamserver$/ ) AND $timeFilter GROUP BY time($__interval), \"instance\" fill(linear)",
     "select": [
      [
       { "params": [ "Percent_Free_Space" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$vboserver$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 20 },
   "yaxes": [
    { "format": "decbytes", "label": "Net Usage in bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes received" ], "type": "alias" }
      ],
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$veeamserver$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "vmxnet3 Ethernet Adapter" }
     ]
    }
   ]
  },
  {
   "title": "$veeamserver v$veeamversionM ($veeamversion) - Backup Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "veeamserver"
  },
  {
   "title": "$backupjob - Last Result",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "repeat": "backupjob",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_veeamBackupSessionsName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_em_job_sessions",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
      { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" }
     ]
    }
   ]
  },
  {
   "title": "$$veeamserver v$veeamversionM ($veeamversion) - Replica Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "veeamserver"
  },
  {
   "title": "$replicajob - Last Result",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "repeat": "replicajob",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_veeamReplicaSessionsName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamReplicaSessionsName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_em_job_sessions",
     "query": "SELECT last(\"veeamReplicaSessionsJobResult\") FROM \"veeam_em_job_sessions\" WHERE (\"veeamReplicaSessionsName\" =~ /^$replicajob$/ AND \"veeamVBR\" =~ /^$veeamserver$/) AND $timeFilter GROUP BY time($__interval), \"veeamReplicaSessionsName\" fill(none)",
     "select": [
      [
       { "params": [ "veeamReplicaSessionsJobResult" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamReplicaSessionsName", "operator": "=~", "value": "/^$replicajob$/" },
      { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" }
     ]
    }
   ]
  },
  {
   "title": "$veeamserver v$veeamversionM ($veeamversion) - Protected VMs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "veeamserver"
  },
  {
   "title": "$backupvm",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 35 },
   "repeat": "backupvm",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_veeamBackupSessionsVmDisplayName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      {
       "params": [
        "veeamBackupSessionsVmDisplayName"
       ],
       "type": "tag"
      },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_em_job_sessionsvm",
     "select": [
      [
       { "params": [ "veeamBackupSessionsJobVMResult" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "veeamBackupSessionsVmDisplayName",
       "operator": "=~",
       "value": "/^$backupvm$/"
      },
      { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" }
     ]
    }
   ]
  },
  {
   "title": "$veeamserver v$veeamversionM ($veeamversion) - Replicated VMs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "repeat": "veeamserver"
  },
  {
   "title": "$replicavm",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 40 },
   "repeat": "replicavm",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_veeamReplicaSessionsVmDisplayName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      {
       "params": [
        "veeamReplicaSessionsVmDisplayName"
       ],
       "type": "tag"
      },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_em_job_sessionsvm",
     "select": [
      [
       {
        "params": [
         "veeamReplicaSessionsJobVMResult"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "veeamReplicaSessionsVmDisplayName",
       "operator": "=~",
       "value": "/^$replicavm$/"
      }
     ]
    }
   ]
  },
  {
   "title": "$veeamserver v$veeamversionM ($veeamversion) - Job Historical Performance and Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "repeat": "veeamserver"
  },
  {
   "title": "Job Historical Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "alias": "$tag_veeamBackupSessionsName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_em_job_sessions",
     "select": [
      [
       { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
      { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Duration (All type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "s", "label": "Job Duration" }
   ],
   "targets": [
    {
     "alias": "$tag_veeamBackupSessionsName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamBackupSessionsName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_em_job_sessions",
     "select": [
      [
       {
        "params": [
         "veeamBackupSessionsTimeDuration"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamBackupSessionsName", "operator": "=~", "value": "/^$backupjob$/" },
      { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" }
     ]
    },
    {
     "alias": "$tag_veeamReplicaSessionsName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamReplicaSessionsName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_em_job_sessions",
     "select": [
      [
       { "params": [ "veeamReplicaSessionsDuration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamReplicaSessionsName", "operator": "=~", "value": "/^$replicajob$/" },
      { "condition": "AND", "key": "veeamVBR", "operator": "=~", "value": "/^$veeamserver$/" }
     ]
    }
   ]
  }
 ]
}